import * as THREE from 'three';

export function createMeadow(canvas, onActivity, marketplaceAgents = []) {
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.34;
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  const scene = new THREE.Scene();
  scene.background = makeSkyGradient();
  scene.fog = new THREE.Fog('#7483b1', 40, 108);
  const camera = new THREE.PerspectiveCamera(55, 1, .1, 160);
  camera.position.set(0, 7.8, 16);
  const controls = { azimuth: -.28, target: -.28, dragging: false, x: 0 };
  const explorer = new THREE.Vector3(-2.7, 0, 2.2), heldKeys = new Set();
  let authenticated = false, nearbyTarget = null;
  const hemi = new THREE.HemisphereLight('#e5dcff', '#163a56', 2.4); scene.add(hemi);
  const sun = new THREE.DirectionalLight('#ffe1b2', 3.8); sun.position.set(-11, 14, 4); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun);
  const pink = new THREE.PointLight('#ff68ba', 18, 14); pink.position.set(2, 3.5, 1); scene.add(pink);
  const violet = new THREE.PointLight('#9573ff', 12, 18); violet.position.set(-5, 4, -8); scene.add(violet);
  const meadow = new THREE.Mesh(new THREE.CircleGeometry(72, 160), new THREE.MeshStandardMaterial({ color: '#416e69', roughness: .86, metalness:.03 }));
  meadow.rotation.x = -Math.PI / 2; scene.add(meadow);
  const path = new THREE.Mesh(new THREE.CircleGeometry(3.35, 64), new THREE.MeshStandardMaterial({ color: '#c9c6b4', roughness: .82, metalness:.05 })); path.rotation.x = -Math.PI / 2; path.position.y = .012; path.receiveShadow=true; scene.add(path);
  const table = new THREE.Group(); table.position.set(0, .55, 0); scene.add(table);
  const top = new THREE.Mesh(new THREE.CylinderGeometry(1.75, 1.9, .22, 32), new THREE.MeshStandardMaterial({ color: '#29345f', roughness: .28, metalness:.42 })); top.castShadow=true; table.add(top);
  const leg = new THREE.Mesh(new THREE.CylinderGeometry(.35, .47, 1.12, 12), new THREE.MeshStandardMaterial({ color: '#182343', roughness: .42, metalness:.48 })); leg.position.y = -.62; table.add(leg);
  const cards = new THREE.Group(); cards.position.y=.18; table.add(cards); for(let i=0;i<4;i++){const c=new THREE.Mesh(new THREE.BoxGeometry(.55,.035,.75),new THREE.MeshStandardMaterial({color:i%2?'#a98cff':'#d9ff4f',emissive:i%2?'#513cc5':'#6b9f00',emissiveIntensity:.25,roughness:.28,metalness:.25}));c.position.set(Math.cos(i*1.57)*.75,.02,Math.sin(i*1.57)*.75);c.rotation.y=i*.6;cards.add(c)}
  addLandscape(scene); addAtmosphere(scene); addDistantHills(scene); addCapitalTrails(scene);
  const agents = [
    makeWildling('#ff7f9f','#ffcb86','Nori · match scout',[-2.15,.55,.2],.93),
    makeWildling('#64afea','#6ce0db','Vela · warm intros',[2.22,.55,-.18],.93),
    makeWildling('#67bd78','#d5ed79','Moss · story keeper',[.1,.55,-2.25],.83),
    makeWildling('#b886ea','#f2caff','Luma · investor map',[-11,.55,-6],.9),
    makeWildling('#f6a65c','#ffe09b','Pip · application runner',[9,.55,-8],.78),
    makeWildling('#ee6f91','#ffd2dc','Rumi · narrative coach',[14,.55,5],.96),
    makeWildling('#4fc6c4','#b8f5de','Sora · diligence scout',[-16,.55,7],.88),
    makeWildling('#7989e8','#d6ddff','Kito · reply tracker',[-4,.55,-17],.82),
    makeWildling('#d278b7','#ffd1e9','Nova · accelerator fit',[7,.55,17],.91),
    makeWildling('#e7a84d','#fff0a4','Omi · deck builder',[-20,.55,-13],.85),
    makeWildling('#52a9e8','#c6efff','Tali · partner signal',[20,.55,-14],.87),
    makeWildling('#8ac96b','#e6f6ad','Mika · founder liaison',[22,.55,14],.94)
  ];
  const profiles = [
    { startup: 'Kiteframe', industry: 'Climate SaaS', public: 'Comparing investor fit signals with Vela.', private: 'Shortlisting 12 climate funds for a partner intro.', badges: ['12 investor fits', '3 warm intros', 'Seed'] },
    { startup: 'Aster Health', industry: 'Healthtech', public: 'Passing a warm-intro pattern to Nori.', private: 'Rewriting the opening note for 8 operator angels.', badges: ['8 warm replies', '2 partner calls', 'Pre-seed'] },
    { startup: 'Nomi Labs', industry: 'AI infrastructure', public: 'Turning the circle’s notes into a tighter story.', private: 'Version 4 of the pitch is ready for founder review.', badges: ['Pitch v4', '6 applications', '1 accepted'] },
    { startup: 'Bramble', industry: 'Fintech', public: 'Trading two investor maps with the meadow.', private: 'Found three funds with matching check sizes and thesis.', badges: ['14 investor fits', 'Seed', 'Map shared'] },
    { startup: 'Nudge Systems', industry: 'Enterprise AI', public: 'Running a new application route with Pip.', private: 'Submitted four tailored applications and queued two follow-ups.', badges: ['4 submitted', '2 queued', 'Series A'] },
    { startup: 'Tidehouse', industry: 'Climate', public: 'Testing the founder story against live reactions.', private: 'The climate narrative now has a clear traction-to-ask bridge.', badges: ['Story tested', '9 replies', 'Seed'] },
    { startup: 'Carekind', industry: 'Healthtech', public: 'Checking which investors are actively meeting founders.', private: 'Flagged five partner calendars with a relevant focus.', badges: ['5 signals', '1 intro', 'Pre-seed'] },
    { startup: 'Threadline', industry: 'Developer tools', public: 'Collecting replies from the last outreach wave.', private: 'Two partners opened the deck and one asked for a call.', badges: ['2 deck opens', '1 call', 'Seed'] },
    { startup: 'Kora', industry: 'Consumer', public: 'Comparing accelerator programs over a shared deck.', private: 'Matched three programs to the founder’s traction profile.', badges: ['3 programs', 'Deck ready', 'Pre-seed'] },
    { startup: 'Datum Grove', industry: 'Data', public: 'Polishing a new founder deck inside the grove.', private: 'Rearranged the deck around the strongest investor proof point.', badges: ['Deck v5', '6 slides tuned', 'Seed'] },
    { startup: 'Latticewell', industry: 'Future of work', public: 'Listening for warm-intro signals across the meadow.', private: 'Found a second-degree path to a partner at the target fund.', badges: ['Warm path', '7 targets', 'Series A'] },
    { startup: 'Daymark', industry: 'Education', public: 'Helping a fellow founder rehearse their accelerator story.', private: 'Prepared a program-specific application and feedback checklist.', badges: ['1 accepted', '2 applications', 'Seed'] }
  ];
  agents.forEach((agent, i) => {
    const listing = marketplaceAgents[i];
    scene.add(agent.group);
    agent.profile = listing ? {
      startup: listing.name,
      industry: listing.type || 'Marketplace agent',
      public: listing.description || 'A resident agent is active in the marketplace.',
      private: listing.description || 'This agent is ready to join your founder workflow.',
      badges: [listing.status || 'published', listing.performance || 'active', listing.type || 'Agent'],
    } : profiles[i];
    agent.kind='agent'; agent.group.userData={target:agent}; agent.group.rotation.y = i === 0 ? .55 : i === 1 ? -.55 : Math.PI;
  });
  const houses = [
    makeCapitalHouse({name:'Verdant House', subtitle:'CLIMATE & INDUSTRIAL', position:[-17,0,-11], color:'#69b879', light:'#e4f39a', profile:{industry:'Climate & industrial',public:'Verdant House is opening its seed-stage signal room.',private:'Open this week: climate and industrial tools with early B2B traction.',badges:['Seed focus','£250k–£2m','3 active paths']}}),
    makeCapitalHouse({name:'Signal House', subtitle:'AI & INFRASTRUCTURE', position:[17,0,-12], color:'#7888df', light:'#c9d2ff', profile:{industry:'AI & infrastructure',public:'Signal House is listening for technical founder stories.',private:'Partner office hour opens Friday for AI infrastructure and devtools.',badges:['Partner office hour','Pre-seed–A','8 active paths']}}),
    makeCapitalHouse({name:'Care House', subtitle:'HEALTH & WELLBEING', position:[-18,0,14], color:'#e38d9c', light:'#ffe0bd', profile:{industry:'Health & wellbeing',public:'Care House is reviewing evidence-first founder narratives.',private:'The House is seeking clinical insight, evidence and a clear care pathway.',badges:['Health thesis','Rolling review','2 warm paths']}}),
    makeCapitalHouse({name:'Launch Grove', subtitle:'ACCELERATOR GUILD', position:[18,0,15], color:'#e5a94d', light:'#fff0aa', profile:{industry:'Accelerators',public:'Launch Grove is preparing the next founder cohort.',private:'Applications are open for founders with a sharp problem, team and first proof.',badges:['Applications open','Cohort 09','Founder office hours']}})
  ];
  houses.forEach(house=>{scene.add(house.group);house.kind='house';house.group.userData={target:house}});
  const explorerMarker = makeExplorerMarker(); scene.add(explorerMarker);
  const pulse = new THREE.Mesh(new THREE.SphereGeometry(.13, 20, 16),new THREE.MeshStandardMaterial({color:'#fff08a',emissive:'#ffd26d',emissiveIntensity:1.4})); pulse.position.set(0,1.1,0); scene.add(pulse);
  const arc = new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-1.55,1.2,.2),new THREE.Vector3(0,2.2,-.2),new THREE.Vector3(1.55,1.2,-.1)]),new THREE.LineDashedMaterial({color:'#fff4b0',dashSize:.16,gapSize:.1}));arc.computeLineDistances();scene.add(arc);
  const ray = new THREE.Raycaster(), pointer = new THREE.Vector2();
  canvas.addEventListener('pointerdown', e => { controls.dragging=true; controls.x=e.clientX; });
  addEventListener('pointerup', () => controls.dragging=false);
  addEventListener('pointermove', e => { if(controls.dragging){ controls.target += (e.clientX-controls.x)*.006; controls.x=e.clientX; } pointer.x=e.clientX/innerWidth*2-1; pointer.y=-(e.clientY/innerHeight)*2+1; });
  canvas.addEventListener('click', () => { ray.setFromCamera(pointer,camera); const hit=ray.intersectObjects([...agents,...houses].map(a=>a.group),true)[0]; if(hit){let root=hit.object; while(root.parent&&root.parent!==scene)root=root.parent; const target=root.userData.target; if(target) publishEncounter(target,true);} });
  addEventListener('keydown', e => { if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)) return; const key=e.key.toLowerCase(); if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){heldKeys.add(key);e.preventDefault()} if(key==='enter'&&nearbyTarget)publishEncounter(nearbyTarget,true); });
  addEventListener('keyup', e => heldKeys.delete(e.key.toLowerCase()));
  function publishEncounter(target, force=false){if(!force&&nearbyTarget===target)return;nearbyTarget=target;const p=target.profile;const prefix=target.kind==='house'?'Capital House':'Wildling';const displayName=p.startup || target.name;onActivity(authenticated?{title:`${displayName} · ${prefix}`,detail:p.private,meta:{industry:p.industry,badges:p.badges,locked:false}}:{title:`${displayName} · ${prefix}`,detail:p.public,meta:{industry:'Log in to reveal thesis',badges:['Preview only'],locked:true}})}
  let clock = new THREE.Clock(), elapsed=0; function render(){const dt=Math.min(clock.getDelta(),.05),t=elapsed+=dt;const step=dt*4.8; if(heldKeys.has('arrowup')||heldKeys.has('w'))explorer.z-=step;if(heldKeys.has('arrowdown')||heldKeys.has('s'))explorer.z+=step;if(heldKeys.has('arrowleft')||heldKeys.has('a'))explorer.x-=step;if(heldKeys.has('arrowright')||heldKeys.has('d'))explorer.x+=step;explorer.x=THREE.MathUtils.clamp(explorer.x,-42,42);explorer.z=THREE.MathUtils.clamp(explorer.z,-42,42);controls.azimuth+=(controls.target-controls.azimuth)*.05;camera.position.x=explorer.x+Math.sin(controls.azimuth)*14.5;camera.position.y=7.8;camera.position.z=explorer.z+Math.cos(controls.azimuth)*14.5;camera.lookAt(explorer.x,.45,explorer.z-1.5);explorerMarker.position.set(explorer.x,.05,explorer.z);explorerMarker.rotation.z-=.025;let nearest=null,best=3.6;agents.forEach((a,i)=>{a.group.position.y=.55+Math.sin(t*1.7+i)*.075;a.group.rotation.y+=(i===2?.004:-.004);a.animate?.(t+i*.8);const distance=Math.hypot(a.group.position.x-explorer.x,a.group.position.z-explorer.z);if(distance<best){best=distance;nearest=a}});houses.forEach(h=>{h.animate(t);const distance=Math.hypot(h.group.position.x-explorer.x,h.group.position.z-explorer.z);if(distance<5.8&&distance<best){best=distance;nearest=h}});if(nearest)publishEncounter(nearest);else if(nearbyTarget){nearbyTarget=null;onActivity({title:'Explore the living meadow',detail:'Walk toward a glowing Wildling or Capital House to overhear an agent exchange.',meta:{industry:'Guest preview',badges:['← ↑ ↓ → move'],locked:true}})}pulse.scale.setScalar(1+Math.sin(t*3)*.2);pulse.position.x=Math.sin(t*1.2)*.32;pulse.position.z=Math.cos(t*1.2)*.32;renderer.render(scene,camera);requestAnimationFrame(render)}
  function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();render();
  return { setAuthenticated(value){authenticated=value;if(nearbyTarget)publishEncounter(nearbyTarget,true)}, addFounderWildling({description,stage,goal}) { const seed=hash(description); const colors=[['#a986ee','#e6bcff'],['#f5a45e','#ffdfa3'],['#55c6d3','#a7f0ed']][seed%3]; const founder=makeWildling(colors[0],colors[1],'Your Wildling',[0,.55,2.6],.88); founder.kind='agent';founder.profile={startup:'Your startup',industry:'Founder profile',public:'A new Wildling has arrived at the meadow.',private:`Building a path to ${goal}.`,badges:[stage,goal,'Just joined']};founder.group.rotation.y=Math.PI; founder.group.userData={target:founder}; scene.add(founder.group); agents.push(founder); } };
}
function makeWildling(main,light,name,[x,y,z],scale){
  const group=new THREE.Group(); group.position.set(x,y,z); group.scale.setScalar(scale);
  const skin=new THREE.MeshPhysicalMaterial({color:main,roughness:.31,metalness:.07,clearcoat:.42,clearcoatRoughness:.22});
  const soft=new THREE.MeshPhysicalMaterial({color:light,roughness:.37,metalness:.02,clearcoat:.24});
  const night=new THREE.MeshStandardMaterial({color:'#17203d',roughness:.29,metalness:.22});
  const eyeWhite=new THREE.MeshStandardMaterial({color:'#f5f7ff',roughness:.2});
  const pupil=new THREE.MeshStandardMaterial({color:'#17203d',roughness:.15,metalness:.1});
  const glow=new THREE.MeshStandardMaterial({color:light,roughness:.16,emissive:light,emissiveIntensity:.58});
  const motions=[]; let head,body; const kind=name.split(' ')[0];
  const part=(geometry,material,position=[0,0,0],shape=[1,1,1])=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(...position);mesh.scale.set(...shape);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);return mesh};
  const sphere=(radius,material,position,shape=[1,1,1])=>part(new THREE.SphereGeometry(radius,32,24),material,position,shape);
  const capsule=(radius,length,material,position,shape=[1,1,1])=>part(new THREE.CapsuleGeometry(radius,length,8,16),material,position,shape);
  const face=(y,z,width=.31,expression=0)=>{for(const side of[-1,1]){const eye=sphere(.15,eyeWhite,[side*width,y,z],[.82,1.12,.3]);sphere(.078,pupil,[side*(width+.015),y-.01,z+.09],[.65,.9,.22]);sphere(.025,glow,[side*(width+.03),y+.035,z+.125],[1,1,.4]);if(expression)eye.rotation.z=side*expression}return sphere(.115,soft,[0,y-.24,z+.02],[1.35,.72,.55])};
  const paw=(side,y,z,angle=0)=>{const arm=capsule(.095,.34,skin,[side*.58,y,z]);arm.rotation.z=side*angle;const hand=sphere(.12,soft,[side*.7,y-.22,z+.05],[1,.8,.82]);return{arm,hand}};

  if(kind==='Nori'){ // lynx-like match scout
    body=sphere(.55,skin,[0,0,0],[.9,1.06,.78]);head=sphere(.48,skin,[0,.7,.04],[1.07,.94,.88]);
    [-1,1].forEach(side=>{const ear=part(new THREE.ConeGeometry(.19,.52,5),skin,[side*.31,1.21,.02]);ear.rotation.z=side*.12;const inner=part(new THREE.ConeGeometry(.10,.31,4),soft,[side*.31,1.24,.11]);inner.rotation.z=side*.12});face(.76,.47,.25,.13);const tail=part(new THREE.TorusGeometry(.42,.09,10,28,Math.PI*1.35),skin,[.49,-.06,-.25]);tail.rotation.set(.18,-.52,.08);motions.push(t=>tail.rotation.y=-.52+Math.sin(t*2)*.17);[-1,1].forEach(side=>{const p=paw(side,.02,.06,.44);motions.push(t=>p.arm.rotation.z=side*(.44+Math.sin(t*1.7)*.12))});
  } else if(kind==='Vela'){ // feathered courier
    body=sphere(.61,skin,[0,.02,0],[.78,1.14,.78]);head=sphere(.39,soft,[0,.83,.13],[.88,.95,.8]);face(.87,.47,.2,-.06);const beak=part(new THREE.ConeGeometry(.15,.34,5),glow,[0,.74,.55]);beak.rotation.x=Math.PI/2;[-1,1].forEach((side,i)=>{const wing=part(new THREE.SphereGeometry(.42,24,16),skin,[side*.57,.1,-.01],[.45,1.4,.24]);wing.rotation.z=side*.54;const feather=part(new THREE.ConeGeometry(.12,.52,5),soft,[side*.76,.15,.03]);feather.rotation.z=side*.85;motions.push(t=>{wing.rotation.z=side*(.54+Math.sin(t*3+i)*.21);feather.rotation.z=side*(.85+Math.sin(t*3+i)*.17)})});for(const px of[-.17,0,.17]){const crest=part(new THREE.ConeGeometry(.08,.3,5),skin,[px,1.26,.03]);crest.rotation.z=-px*1.4}
  } else if(kind==='Moss'){ // rounded moss guardian
    body=sphere(.72,skin,[0,-.02,0],[1.15,.72,.94]);head=sphere(.39,soft,[.15,.48,.38],[1.15,.85,.72]);face(.5,.72,.17,.02);const shell=sphere(.64,night,[0,.2,-.18],[1.16,.72,.42]);for(let i=0;i<5;i++){const shard=part(new THREE.ConeGeometry(.12,.38,5),glow,[Math.cos(i*1.26)*.41,.5,Math.sin(i*1.26)*.27-.18]);shard.rotation.z=Math.cos(i*1.26)*.6}[-1,1].forEach(side=>{const horn=part(new THREE.ConeGeometry(.12,.38,5),glow,[side*.22,.94,.25]);horn.rotation.z=side*.42;const foot=sphere(.22,soft,[side*.38,-.42,.22],[1.2,.55,.9]);motions.push(t=>foot.position.y=-.42+Math.sin(t*2+(side>0?0:1))*.03)});
  } else if(kind==='Luma'){ // moth cartographer
    body=sphere(.38,night,[0,.05,0],[.72,1.35,.72]);head=sphere(.32,soft,[0,.65,.08],[1.04,.92,.85]);face(.68,.39,.16,.1);[-1,1].forEach((side,i)=>{const wing=part(new THREE.CircleGeometry(.68,20),skin,[side*.55,.22,-.07],[.82,1.15,1]);wing.rotation.y=side*.36;const spot=sphere(.13,glow,[side*.67,.3,.0],[1.1,1,.18]);motions.push(t=>wing.rotation.y=side*(.36+Math.sin(t*2.5+i)*.15));group.add(spot)});for(const side of[-1,1]){const antenna=capsule(.026,.28,glow,[side*.12,1.04,.08]);antenna.rotation.z=side*.32}
  } else if(kind==='Pip'){ // amphibian application runner
    body=sphere(.58,skin,[0,-.08,0],[1.14,.77,.92]);head=sphere(.52,skin,[0,.35,.26],[1.08,.78,.78]);face(.49,.62,.28,-.1);[-1,1].forEach(side=>{const eyeStem=sphere(.16,soft,[side*.29,.73,.25],[1,1,.75]);const web=part(new THREE.ConeGeometry(.13,.32,4),soft,[side*.43,-.34,.3]);web.rotation.z=side*.85;motions.push(t=>web.rotation.z=side*(.85+Math.sin(t*2+side)*.12))});const tongue=part(new THREE.CapsuleGeometry(.035,.19,4,8),glow,[0,.22,.76]);tongue.rotation.x=Math.PI/2;
  } else if(kind==='Rumi'){ // fox narrative coach
    body=sphere(.49,skin,[0,0,0],[.9,1.18,.72]);head=sphere(.46,skin,[0,.78,.08],[1.05,.93,.84]);[-1,1].forEach(side=>{const ear=part(new THREE.ConeGeometry(.18,.58,5),skin,[side*.29,1.27,.04]);ear.rotation.z=side*.1;part(new THREE.ConeGeometry(.09,.34,4),soft,[side*.29,1.30,.15])});face(.83,.48,.25,.08);const tail=sphere(.42,soft,[.54,-.18,-.19],[1.65,.5,.55]);motions.push(t=>tail.rotation.y=Math.sin(t*2)*.22);[-1,1].forEach(side=>{const p=paw(side,.02,.04,.34);motions.push(t=>p.arm.rotation.z=side*(.34+Math.sin(t*1.7+side)*.13))});
  } else if(kind==='Sora'){ // owl diligence scout
    body=sphere(.68,skin,[0,.02,0],[.9,1.08,.75]);head=sphere(.59,soft,[0,.64,.06],[1.1,.85,.8]);[-1,1].forEach(side=>{const disc=sphere(.27,night,[side*.25,.7,.49],[1,1,.22]);const eye=sphere(.13,eyeWhite,[side*.25,.7,.57],[1,1,.16]);const iris=sphere(.07,pupil,[side*.25,.7,.64],[1,1,.08]);group.add(disc,eye,iris)});const beak=part(new THREE.ConeGeometry(.1,.22,5),glow,[0,.54,.66]);beak.rotation.x=Math.PI/2;[-1,1].forEach((side,i)=>{const wing=sphere(.3,skin,[side*.52,.1,0],[.6,1.55,.42]);wing.rotation.z=side*.44;motions.push(t=>wing.rotation.z=side*(.44+Math.sin(t*2+i)*.13))});
  } else if(kind==='Kito'){ // gecko reply tracker
    body=sphere(.54,skin,[0,.02,0],[1.3,.62,.7]);head=sphere(.4,soft,[.37,.34,.18],[1.16,.74,.72]);face(.39,.54,.17,-.07);const tail=part(new THREE.TorusGeometry(.52,.09,9,24,Math.PI*1.58),skin,[-.63,-.06,-.14]);tail.rotation.set(.18,.7,.1);motions.push(t=>tail.rotation.y=.7+Math.sin(t*2.3)*.25);[-1,1].forEach(side=>{const foot=sphere(.16,soft,[side*.37,-.35,.2],[1.55,.45,.65]);motions.push(t=>foot.position.y=-.35+Math.sin(t*3+(side>0?0:1))*.04)});
  } else if(kind==='Nova'){ // luminous cloud oracle
    body=sphere(.55,skin,[0,0,0],[1,1,.86]);head=sphere(.43,soft,[0,.6,.06],[1.06,.85,.8]);face(.65,.43,.21,.03);for(let i=0;i<7;i++){const mote=sphere(.075,glow,[Math.cos(i*.9)*.74,.58+Math.sin(i*1.4)*.44,Math.sin(i*.9)*.35],[1,1,1]);motions.push(t=>{mote.position.y=.58+Math.sin(t*1.6+i)*.44;mote.position.x=Math.cos(t*.8+i)*.74})}const halo=part(new THREE.TorusGeometry(.55,.025,8,28),glow,[0,1.25,0]);halo.rotation.x=Math.PI/2;motions.push(t=>halo.rotation.z=t*.7);
  } else if(kind==='Omi'){ // beetle deck builder
    body=sphere(.57,night,[0,.02,0],[1.08,.78,.82]);head=sphere(.32,skin,[0,.43,.44],[.92,.75,.7]);face(.46,.68,.16,.02);const shell=sphere(.48,skin,[0,.22,-.13],[1,.65,.52]);[-1,1].forEach(side=>{for(let i=0;i<3;i++){const leg=capsule(.05,.3,soft,[side*(.48+i*.04),-.12-i*.12,-.04]);leg.rotation.z=side*(.9-i*.16);motions.push(t=>leg.rotation.z=side*(.9-i*.16+Math.sin(t*3+i)*.08))}const antenna=capsule(.025,.26,glow,[side*.12,.78,.36]);antenna.rotation.z=side*.42});
  } else if(kind==='Tali'){ // otter partner signal
    body=sphere(.52,skin,[0,0,0],[.82,1.18,.72]);head=sphere(.43,soft,[0,.67,.11],[1,.9,.8]);face(.72,.49,.2,.05);[-1,1].forEach(side=>{const ear=sphere(.11,skin,[side*.31,1.02,.06],[1,.72,.75]);const p=paw(side,.13,.13,.22);motions.push(t=>p.arm.rotation.z=side*(.22+Math.sin(t*1.8+side)*.14))});const tail=sphere(.33,skin,[0,-.42,-.35],[.55,1.55,.55]);tail.rotation.x=-.45;motions.push(t=>tail.rotation.y=Math.sin(t*1.8)*.25);
  } else { // Mika: antlered founder liaison
    body=sphere(.53,skin,[0,0,0],[.86,1.13,.7]);head=sphere(.4,soft,[0,.68,.1],[1,.03+.86,.78]);face(.73,.48,.2,-.03);[-1,1].forEach(side=>{const antler=capsule(.035,.52,glow,[side*.25,1.2,.02]);antler.rotation.z=side*.35;const branch=capsule(.025,.18,glow,[side*.38,1.34,.02]);branch.rotation.z=side*1.05;const hoof=sphere(.15,night,[side*.27,-.45,.16],[1.2,.42,.8]);motions.push(t=>hoof.position.y=-.45+Math.sin(t*2+(side>0?0:1))*.025)});
  }
  const label=makeLabel(name);label.position.set(0,-.98,0);group.add(label);
  return{group,name,detail:name.includes('Nori')?'Sharing 12 investor matches with the circle.':name.includes('Vela')?'Tailoring warm-intro notes from everyone’s signals.':name.includes('Moss')?'Refining the shared founder narrative.':'Meeting the resident agents and mapping your next moves.',animate(t){head.rotation.z=Math.sin(t*1.12)*.045;body.scale.y=1+Math.sin(t*2.1)*.025;motions.forEach(fn=>fn(t))}}}
function orb(radius,material,scale){const mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,32,24),material);mesh.scale.set(...scale);mesh.castShadow=true;mesh.receiveShadow=true;return mesh}
function makeExplorerMarker(){const marker=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(.38,.028,8,32),new THREE.MeshBasicMaterial({color:'#fff7b0'})),arrow=new THREE.Mesh(new THREE.ConeGeometry(.08,.22,8),new THREE.MeshBasicMaterial({color:'#ff78ad'}));ring.rotation.x=Math.PI/2;arrow.position.y=.22;marker.add(ring,arrow);return marker}
function makeCapitalHouse({name,subtitle,position,color,light,profile}){const group=new THREE.Group(),baseMat=new THREE.MeshStandardMaterial({color,roughness:.25,metalness:.55}),lightMat=new THREE.MeshStandardMaterial({color:light,roughness:.18,metalness:.25,emissive:light,emissiveIntensity:.3}),portalMat=new THREE.MeshStandardMaterial({color:light,roughness:.12,emissive:light,emissiveIntensity:1.5});group.position.set(...position);const plaza=new THREE.Mesh(new THREE.CylinderGeometry(3.25,3.5,.18,48),new THREE.MeshStandardMaterial({color:'#253451',roughness:.52,metalness:.24}));plaza.position.y=.09;plaza.receiveShadow=true;group.add(plaza);const hall=new THREE.Mesh(new THREE.CylinderGeometry(1.72,1.95,1.6,32),baseMat);hall.position.y=.9;hall.castShadow=true;group.add(hall);const dome=new THREE.Mesh(new THREE.SphereGeometry(1.78,32,18),lightMat);dome.position.y=1.72;dome.scale.set(1,.62,1);dome.castShadow=true;group.add(dome);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.88,1.25,8),baseMat);roof.position.y=2.55;roof.rotation.y=Math.PI/8;group.add(roof);[-1,1].forEach(side=>{const pillar=new THREE.Mesh(new THREE.CylinderGeometry(.17,.22,1.55,12),lightMat);pillar.position.set(side*1.3,.86,1.18);pillar.castShadow=true;group.add(pillar);const lantern=new THREE.Mesh(new THREE.SphereGeometry(.16,16,12),portalMat);lantern.position.set(side*1.3,1.67,1.18);group.add(lantern)});const portal=new THREE.Mesh(new THREE.TorusGeometry(.52,.115,12,28),portalMat);portal.position.set(0,.98,1.94);group.add(portal);const door=new THREE.Mesh(new THREE.CircleGeometry(.48,24),new THREE.MeshBasicMaterial({color:'#10172f'}));door.position.set(0,.98,1.93);group.add(door);const beacon=new THREE.Mesh(new THREE.TorusGeometry(.74,.06,10,32),portalMat);beacon.position.y=3.5;beacon.rotation.x=Math.PI/2;group.add(beacon);const flag=new THREE.Group();flag.position.set(-2.2,2.45,0);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,2.6,8),new THREE.MeshStandardMaterial({color:'#17213d',roughness:.45,metalness:.5}));mast.position.y=-1.2;const cloth=new THREE.Mesh(new THREE.PlaneGeometry(.95,.57,3,1),new THREE.MeshBasicMaterial({color:light,side:THREE.DoubleSide,transparent:true,opacity:.9}));cloth.position.set(.48,-.3,0);flag.add(mast,cloth);group.add(flag);const label=makeLabel(name);label.position.set(0,4.22,0);label.scale.set(2.35,.44,1);group.add(label);const sub=makeLabel(subtitle,true);sub.position.set(0,3.76,0);sub.scale.set(1.4,.2,1);group.add(sub);return{group,name,profile,kind:'house',animate(t){beacon.rotation.z=t*.7;beacon.position.y=3.5+Math.sin(t*2)*.1;portal.scale.setScalar(1+Math.sin(t*2.5)*.08);cloth.rotation.y=Math.sin(t*1.2)*.18}}}
function makeLabel(text,sub=false){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d');ctx.fillStyle='rgba(8,13,37,.7)';ctx.roundRect(8,13,496,70,16);ctx.fill();ctx.fillStyle=sub?'#dfe4ff':'#f5f7ff';ctx.font=`${sub?'500 24px':'600 30px'} monospace`;ctx.textAlign='center';ctx.fillText(text.toUpperCase(),256,58);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));sprite.scale.set(1.55,.29,1);return sprite}
function addLandscape(scene){const trunk=new THREE.MeshStandardMaterial({color:'#263b4c',roughness:.76,metalness:.15}),leafColors=['#245b65','#35756e','#486c86','#5a6493'];for(let i=0;i<160;i++){const a=Math.random()*Math.PI*2,r=9+Math.random()*55;const tree=new THREE.Group();tree.position.set(Math.cos(a)*r,.6,Math.sin(a)*r);const size=.72+Math.random()*.72;const stem=new THREE.Mesh(new THREE.CylinderGeometry(.09*size,.15*size,1.15*size,9),trunk);stem.position.y=.53*size;stem.castShadow=true;tree.add(stem);const leafMat=new THREE.MeshStandardMaterial({color:leafColors[i%leafColors.length],roughness:.47,metalness:.08});const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(size,2),leafMat);crown.position.y=1.42*size;crown.castShadow=true;tree.add(crown);const crownTop=new THREE.Mesh(new THREE.IcosahedronGeometry(size*.66,1),leafMat);crownTop.position.set(size*.13,1.85*size,-size*.06);tree.add(crownTop);scene.add(tree)}for(let i=0;i<1150;i++){const a=Math.random()*Math.PI*2,r=2.8+Math.random()*63;const flower=new THREE.Mesh(new THREE.SphereGeometry(.035+Math.random()*.055,8,6),new THREE.MeshBasicMaterial({color:['#ff78b5','#d9ff4f','#a98cff','#9de7e0'][i%4]}));flower.position.set(Math.cos(a)*r,.08,Math.sin(a)*r);flower.scale.y=.5;scene.add(flower)}}
function addDistantHills(scene){const colors=['#274a68','#38536e','#4c5b81'];for(let i=0;i<18;i++){const hill=new THREE.Mesh(new THREE.SphereGeometry(6+(i%3)*2,18,10),new THREE.MeshStandardMaterial({color:colors[i%colors.length],roughness:.78,metalness:.08}));const a=i/18*Math.PI*2,r=52+(i%3)*5;hill.position.set(Math.cos(a)*r,-4,Math.sin(a)*r);hill.scale.set(1,.42,.75);scene.add(hill)}}
function addCapitalTrails(scene){const trailMat=new THREE.MeshStandardMaterial({color:'#536e79',roughness:.42,metalness:.4,emissive:'#294b54',emissiveIntensity:.18});[[-17,-11],[17,-12],[-18,14],[18,15]].forEach(([x,z],i)=>{const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,.04,0),new THREE.Vector3(x*.32,.045,z*.1),new THREE.Vector3(x*.68,.045,z*.62),new THREE.Vector3(x,.045,z)]);const trail=new THREE.Mesh(new THREE.TubeGeometry(curve,30,.32,7,false),trailMat);trail.receiveShadow=true;scene.add(trail);const sign=new THREE.Mesh(new THREE.CylinderGeometry(.1,.13,.8,8),new THREE.MeshStandardMaterial({color:['#d9ff4f','#a98cff','#ff8cbd','#8fe2e4'][i],roughness:.22,emissive:['#93a800','#4f3fbd','#b2316c','#2b8d91'][i],emissiveIntensity:.5}));sign.position.set(x*.55,.42,z*.55);scene.add(sign)})}
function addAtmosphere(scene){
  const cloudMat=new THREE.MeshBasicMaterial({color:'#d8dcff',transparent:true,opacity:.24});
  for(let i=0;i<4;i++){const cloud=new THREE.Group();cloud.position.set(-8+i*4.7,6.5+(i%2),-8-i);for(let j=0;j<3;j++){const puff=new THREE.Mesh(new THREE.SphereGeometry(.58+j*.09,16,10),cloudMat);puff.position.set(j*.48,j%2*.15,0);puff.scale.z=.42;cloud.add(puff)}scene.add(cloud)}
  const glowMat=new THREE.MeshBasicMaterial({color:'#d9ff4f'});for(let i=0;i<38;i++){const glow=new THREE.Mesh(new THREE.SphereGeometry(.026,8,6),glowMat);glow.position.set((Math.random()-.5)*14,.5+Math.random()*2.5,(Math.random()-.5)*11);scene.add(glow)}
  const heart=new THREE.Mesh(new THREE.OctahedronGeometry(.18,1),new THREE.MeshStandardMaterial({color:'#d9ff4f',emissive:'#b5e300',emissiveIntensity:1.1,roughness:.18,metalness:.2}));heart.position.set(0,1.7,-.22);scene.add(heart);
  const sparkMat=new THREE.MeshStandardMaterial({color:'#f4f5ff',emissive:'#a98cff',emissiveIntensity:1.5,roughness:.15});const sparks=[0,1,2].map(()=>{const spark=new THREE.Mesh(new THREE.OctahedronGeometry(.09,1),sparkMat);scene.add(spark);return spark});
  const start=performance.now();(function exchange(){const t=(performance.now()-start)/1000;sparks.forEach((spark,i)=>{const p=t*.48+i/3;spark.position.set(Math.sin(p*Math.PI*2)*1.28,1.2+Math.sin(p*Math.PI*4)*.12,-.25+Math.cos(p*Math.PI*2)*.72)});heart.position.y=1.7+Math.sin(t*2)*.08;heart.rotation.y=t;requestAnimationFrame(exchange)})();
}
function makeSkyGradient(){const canvas=document.createElement('canvas');canvas.width=32;canvas.height=512;const ctx=canvas.getContext('2d');const gradient=ctx.createLinearGradient(0,0,0,512);gradient.addColorStop(0,'#282657');gradient.addColorStop(.44,'#6069b2');gradient.addColorStop(.72,'#d68ba4');gradient.addColorStop(1,'#f2b97c');ctx.fillStyle=gradient;ctx.fillRect(0,0,32,512);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h)}
