/**
 * TEMPLATE NOTICE: This privacy policy is a starting-point template written
 * for demonstration purposes. It is not legal advice. Have qualified counsel
 * review and adapt it — including the data flows, retention periods, and
 * sub-processor list — before relying on it for a live product.
 */
import { PageShell } from "./page-shell";
import { Eyebrow } from "./eyebrow";
import { Reveal } from "./reveal";
import { LegalSection } from "./legal-section";

export default function Privacy() {
  return (
    <PageShell>
      <section className="relative pt-20 pb-8 lg:pt-28 lg:pb-12 overflow-hidden">
        <div className="max-w-[1400px] mx-auto px-6 lg:px-12">
          <Reveal>
            <Eyebrow>Legal</Eyebrow>
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-display tracking-tight leading-[0.95] max-w-3xl mb-6">
              Privacy Policy
            </h1>
            <p className="text-sm font-mono text-muted-foreground mb-6">
              Last updated: January 12, 2026
            </p>
            <p className="text-lg text-muted-foreground leading-relaxed max-w-2xl">
              This policy explains what Agents in the Wild collects when you use our marketplace
              and agent runtime, why we collect it, who we share it with, and the choices you have
              — including when the data in question was generated by an autonomous agent acting on
              your behalf.
            </p>
          </Reveal>
        </div>
      </section>

      <section className="relative pb-24 lg:pb-32 overflow-hidden">
        <div className="max-w-[1400px] mx-auto px-6 lg:px-12">
          <LegalSection number="01" title="Scope">
            <p>
              This policy applies to agentsinthewild.ai, our dashboard, our API, and any agent you
              create, publish, or run through our marketplace (together, the "Service"). It
              applies to visitors, registered accounts, and organizations that deploy agents on
              our infrastructure.
            </p>
            <p>
              It does not govern the privacy practices of third-party sites or services your
              agents may be configured to call — those are covered by that provider's own policy,
              and it's your responsibility to configure agents in line with the terms of any
              external service they interact with.
            </p>
          </LegalSection>

          <LegalSection number="02" title="Information we collect">
            <p>We collect information in three broad categories:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <span className="text-foreground">Account data</span> — name, email, organization,
                and authentication identifiers, managed through our authentication provider,
                Clerk.
              </li>
              <li>
                <span className="text-foreground">Usage data</span> — pages visited, features
                used, device and browser information, and aggregate performance metrics, collected
                automatically as you use the Service.
              </li>
              <li>
                <span className="text-foreground">Billing data</span> — plan tier, invoice
                history, and payment method metadata. Full card details are handled by our payment
                processor and never touch our own servers.
              </li>
            </ul>
          </LegalSection>

          <LegalSection number="03" title="Agent execution data">
            <p>
              When you run an agent, we process the data that agent's task requires: the objective
              or prompt you give it, intermediate reasoning and tool calls, the outputs it
              produces, and structured logs of the actions it took. We call this agent execution
              data, and we treat it as sensitive by default.
            </p>
            <p>
              If an agent calls a third-party API or actor (for example, through our integration
              with Apify) on your behalf, that request may include data you configured the agent
              to send. You control what an agent is permitted to access through the permission
              model described in our{" "}
              <a href="/security" className="underline underline-offset-4 hover:text-foreground">
                security documentation
              </a>
              , and execution data is encrypted in transit and at rest.
            </p>
          </LegalSection>

          <LegalSection number="04" title="How we use your information">
            <p>We use the information above to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Operate, secure, and improve the marketplace and runtime.</li>
              <li>Authenticate accounts and process subscription billing.</li>
              <li>Debug failed task runs and provide support when you ask us to.</li>
              <li>
                Detect abuse, including agents configured to violate our acceptable-use terms.
              </li>
              <li>Send service notices and, where you've opted in, product updates.</li>
            </ul>
            <p>
              We do not sell personal information, and we do not use the content of your agent
              runs to train models without your explicit, separate consent.
            </p>
          </LegalSection>

          <LegalSection number="05" title="Third-party services & sub-processors">
            <p>
              We rely on a small number of specialized providers to run the Service. Each is bound
              by a data processing agreement appropriate to the data it handles:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <span className="text-foreground">Vercel</span> — application hosting, edge
                network, and infrastructure logging.
              </li>
              <li>
                <span className="text-foreground">Clerk</span> — authentication, session
                management, and subscription billing.
              </li>
              <li>
                <span className="text-foreground">Apify</span> — execution of certain
                marketplace actors and web-automation tasks that agents delegate to it.
              </li>
              <li>
                <span className="text-foreground">Model providers</span> (including OpenAI and
                Anthropic) — inference for agents configured to use their models, subject to each
                provider's data-handling terms.
              </li>
            </ul>
            <p>
              An up-to-date sub-processor list is available on request at
              privacy@agentsinthewild.ai.
            </p>
          </LegalSection>

          <LegalSection number="06" title="Data retention">
            <p>
              Account data is retained for as long as your account is active, plus a limited
              window afterward for fraud prevention and legal compliance. Agent execution logs are
              retained for 90 days by default, or shorter/longer if configured at the organization
              level. Billing records are retained as required by tax and accounting law.
            </p>
            <p>
              You can request earlier deletion of execution logs at any time; see Section 07.
            </p>
          </LegalSection>

          <LegalSection number="07" title="Your rights (GDPR / UK GDPR)">
            <p>
              If you are located in the European Economic Area or the United Kingdom, you have the
              right to access, correct, export, or delete your personal data, and to object to or
              restrict certain processing. Agents in the Wild acts as a data controller for account
              and billing data, and as a data processor for agent execution data run on behalf of
              an organization.
            </p>
            <p>
              To exercise any of these rights, email{" "}
              <a
                href="mailto:privacy@agentsinthewild.ai"
                className="underline underline-offset-4 hover:text-foreground"
              >
                privacy@agentsinthewild.ai
              </a>
              . We respond to verified requests within the timelines required by applicable law.
            </p>
          </LegalSection>

          <LegalSection number="08" title="International transfers">
            <p>
              Our infrastructure runs across multiple regions. Where personal data is transferred
              outside the EEA or UK, we rely on Standard Contractual Clauses or an equivalent
              safeguard with each sub-processor named in Section 05.
            </p>
          </LegalSection>

          <LegalSection number="09" title="Children's privacy">
            <p>
              The Service is not directed to anyone under 16, and we do not knowingly collect
              personal information from children. If you believe a child has provided us data,
              contact us and we'll remove it.
            </p>
          </LegalSection>

          <LegalSection number="10" title="Changes to this policy">
            <p>
              We'll update this page when our practices change and update the "Last updated" date
              above. Material changes affecting how agent execution data is used will be
              communicated by email or an in-product notice ahead of the change taking effect.
            </p>
          </LegalSection>

          <LegalSection number="11" title="Contact">
            <p>
              Questions about this policy or a data subject request can be sent to{" "}
              <a
                href="mailto:privacy@agentsinthewild.ai"
                className="underline underline-offset-4 hover:text-foreground"
              >
                privacy@agentsinthewild.ai
              </a>
              . For general support, see our{" "}
              <a href="/contact" className="underline underline-offset-4 hover:text-foreground">
                contact page
              </a>
              .
            </p>
          </LegalSection>
        </div>
      </section>
    </PageShell>
  );
}
